
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MY
 */
public class homepage extends javax.swing.JFrame {

    DatabaseHandler handler;
    String currentUser="demouser";
    DefaultListModel listModel;  
    DefaultTableModel tableModel;
    DefaultTableModel historyModel;
    String email;
    String[] listData;
    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        
        this.setLocationRelativeTo(null);
       // String[] data=handler.getBookHistory(currentUser);
      //  JList list=new JList(data);
       // yourBooksPanel.add(list);
        tableModel=(DefaultTableModel) searchTable.getModel();
        historyModel=(DefaultTableModel) historyTable.getModel();
        
    }
     public homepage(String a) {
        initComponents();
        this.setLocationRelativeTo(null);
       // jLabel7.setText(a);
        currentUser=a;
        
        tableModel=(DefaultTableModel) searchTable.getModel();
        historyModel=(DefaultTableModel) historyTable.getModel();
        //getDatabtn.setVisible(false);
        setUpList();
    }

     void setUpList(){
         
         listModel=new DefaultListModel();
        handler= new DatabaseHandler();
        email=handler.getUserEmail(currentUser);
       // listData=handler.getBookHistory(currentUser);
      //  for(int i=0;i<listData.length;i++){
        //    listModel.addElement(Integer.toString(i+1)+") "+listData[i]);
       // }
         try{
       String[][] data = handler.getBookHistory(currentUser);
       
       historyModel.setRowCount(0);
       for(int i=0;i<10;i++){
       
        historyModel.insertRow(historyTable.getRowCount(),new Object[]{
                data[i][0],
                data[i][1]
         });
       }
       
       }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"there is no book with this name");
       }
       
        historyTable.setModel(historyModel);
        System.out.println(email);
     }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchTab = new javax.swing.JTabbedPane();
        yourBooksPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        addBookPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newBook = new javax.swing.JTextField();
        newAuthor = new javax.swing.JTextField();
        addBookbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchBox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 381));
        setSize(new java.awt.Dimension(590, 381));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(810, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("LOG OUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(4336, 16, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Logged IN ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4201, 11, 89, 34));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4082, 11, 67, 34));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("YOUR BOOKS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-760, 198, -1, 30));

        yourBooksPanel.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("YOUR BOOKS");
        yourBooksPanel.add(jLabel9);
        jLabel9.setBounds(60, 20, 100, 20);

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        yourBooksPanel.add(jButton1);
        jButton1.setBounds(500, 290, 63, 23);

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "book name", "author"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(historyTable);

        yourBooksPanel.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 240, 250);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-261909.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        yourBooksPanel.add(jLabel4);
        jLabel4.setBounds(0, -50, 660, 430);

        searchTab.addTab("your books", yourBooksPanel);

        addBookPanel.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 36, 97));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add Book");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 709, 64);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Author");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(46, 118, 121, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Name");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(46, 70, 121, 30);

        newBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookActionPerformed(evt);
            }
        });
        jPanel5.add(newBook);
        newBook.setBounds(185, 80, 227, 30);

        newAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAuthorActionPerformed(evt);
            }
        });
        jPanel5.add(newAuthor);
        newAuthor.setBounds(185, 125, 227, 30);

        addBookbtn.setText("OK");
        addBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookbtnActionPerformed(evt);
            }
        });
        jPanel5.add(addBookbtn);
        addBookbtn.setBounds(240, 190, 47, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\nishant\\oopm miniproject\\DBMS\\DBMS\\images\\pexels-photo-762686.jpeg")); // NOI18N
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, -10, 600, 380);

        addBookPanel.add(jPanel5);
        jPanel5.setBounds(-3, 5, 570, 360);

        searchTab.addTab("add new books", addBookPanel);

        searchPanel.setBackground(new java.awt.Color(255, 255, 0));
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBox.setText("enter book name");
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        searchPanel.add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 300, 30));

        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        searchPanel.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, 30));

        searchTable.setBackground(new java.awt.Color(0, 0, 153));
        searchTable.setForeground(new java.awt.Color(51, 255, 102));
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "book", "author", "user", "user-email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(searchTable);

        searchPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 520, 200));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\nishant\\oopm miniproject\\DBMS\\DBMS\\images\\pexels-photo-46274.jpg")); // NOI18N
        searchPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 350));

        searchTab.addTab("search books", searchPanel);

        jPanel1.add(searchTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        web_page s=new web_page();
        s.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void newBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBookActionPerformed

    private void newAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAuthorActionPerformed

    private void addBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookbtnActionPerformed
        String bkname=newBook.getText();
        String bkauth=newAuthor.getText();

        handler=new DatabaseHandler();
        handler.addBook(bkname,bkauth,currentUser,email);
        setUpList();
       // this.dispose();
    }//GEN-LAST:event_addBookbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
       handler= new DatabaseHandler();
       String bookname=searchBox.getText().toString();
       
       tableModel.setRowCount(0);
       
       try{
       String[][] data = handler.searchBooks(bookname);
       
       for(int i=0;i<10;i++){
       
        tableModel.insertRow(searchTable.getRowCount(),new Object[]{
                data[i][0],
                data[i][1],
                data[i][2],
                data[i][3]
         });
       }
       
       }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"there is no book with this name");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbtnActionPerformed

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row=historyTable.getSelectedRow();
        
        String book=historyTable.getValueAt(row,0).toString();
        handler= new DatabaseHandler();
   
        System.out.println("book to be deleted"+book);
        handler.deleteBook(book,currentUser);
        historyModel.setRowCount(0);
        setUpList();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBookPanel;
    private javax.swing.JButton addBookbtn;
    private javax.swing.JTable historyTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField newAuthor;
    private javax.swing.JTextField newBook;
    private javax.swing.JTextField searchBox;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTabbedPane searchTab;
    private javax.swing.JTable searchTable;
    private javax.swing.JButton searchbtn;
    private javax.swing.JPanel yourBooksPanel;
    // End of variables declaration//GEN-END:variables

    void setUser(String username) {
       currentUser=username;
    }
}
