
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MY
 */
public class sign_up extends javax.swing.JFrame {
    String name=new String();

    /**
     * Creates new form sign_up
     */
    public sign_up() {
        initComponents();
     this.setLocationRelativeTo(null);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_fname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_eid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_uname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_pass = new javax.swing.JPasswordField();
        jButton_register_ = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(694, 577));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("First name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 35, 117, 36);

        jTextField_fname.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jTextField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_fname);
        jTextField_fname.setBounds(145, 35, 183, 36);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Last name");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 89, 117, 36);

        jTextField_lname.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jTextField_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_lname);
        jTextField_lname.setBounds(145, 89, 183, 36);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email ID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 143, 117, 36);

        jTextField_eid.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jTextField_eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_eidActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_eid);
        jTextField_eid.setBounds(145, 143, 183, 36);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 197, 117, 36);

        jTextField_uname.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jTextField_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_unameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_uname);
        jTextField_uname.setBounds(145, 197, 183, 39);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 254, 117, 36);

        jTextField_pass.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jTextField_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_passActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_pass);
        jTextField_pass.setBounds(145, 254, 183, 36);

        jButton_register_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_register_.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_register_.setText("Sign Up");
        jButton_register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_register_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_register_);
        jButton_register_.setBounds(120, 320, 107, 43);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 100, 400, 370);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Already have an account ? ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 50, 220, 79);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SIGN IN");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10);
        jLabel10.setBounds(80, 60, 101, 104);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(380, 160, 290, 230);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("By signing up, you agree to the TERMS AND CONDITIONS and PRIVACY POLICY.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 470, 660, 57);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\nishant\\oopm miniproject\\DBMS\\DBMS\\images\\new.jpg")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 70, 694, 577);

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SIGN UP");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(230, 10, 234, 64);

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(30, 30, 59, 23);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(610, 30, 55, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mohan\\Pictures\\2.PNG")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 728, 73);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, -1, 690, 70);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        login_form s=new login_form();
        this.dispose();
        s.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton_register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_register_ActionPerformed
        String fname=jTextField_fname.getText();
        String lname=jTextField_lname.getText();
        String email=jTextField_eid.getText();
        String uname=jTextField_uname.getText();
        String pass=String.valueOf(jTextField_pass.getPassword());

        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a username");
        }
        else if(pass.equals(""))

        {
            JOptionPane.showMessageDialog(null,"Add a password");
        }

        else if (checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null,"This username already exist");
        }
        else{
            PreparedStatement ps;
            String query="INSERT INTO `users`(`firstname`, `lastname`, `email`, `username`, `password`) VALUES (?,?,?,?,?)";
            try {
                ps= Myconnection.getConnection().prepareStatement(query);

                ps.setString(1,fname);
                ps.setString(2,lname);
                ps.setString(3,email);
                ps.setString(4,uname);
                ps.setString(5,pass);

                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null,"New user added");
                    name=uname;
                    new getting_started(name).setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_register_ActionPerformed

    private void jTextField_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_passActionPerformed

    private void jTextField_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_unameActionPerformed

    private void jTextField_eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_eidActionPerformed
             String email = jTextField_eid.getText();
          if (!email.contains("@")){
              JOptionPane.showMessageDialog(null, "Please enter a valid email id"); 
          
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_eidActionPerformed

    private void jTextField_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnameActionPerformed

    private void jTextField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        web_page s=new web_page();
        s.setVisible(true);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean checkUsername(String username)
    {
        PreparedStatement ps;
       ResultSet rs;
       boolean checkUser =false;
       
       String query="SELECT * FROM users WHERE`username`=?";
       
        try {
            ps=Myconnection.getConnection().prepareStatement(query);
            ps.setString(1,username);
            
            rs=ps.executeQuery();
            
            if(rs.next())
            {
               checkUser =true; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }
     return checkUser;       
    }
    
    public boolean checkUserEmail(String userEmail)
    {
        PreparedStatement ps;
       ResultSet rs;
       boolean checkEmail =false;
       
       String query="SELECT * FROM users WHERE`email`=?";
       
        try {
            ps=Myconnection.getConnection().prepareStatement(query);
            ps.setString(2,userEmail);
            
            rs=ps.executeQuery();
            
            if(rs.next())
            {
               checkEmail =true; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }
     return checkEmail;       
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_register_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField_eid;
    private javax.swing.JTextField jTextField_fname;
    private javax.swing.JTextField jTextField_lname;
    private javax.swing.JPasswordField jTextField_pass;
    private javax.swing.JTextField jTextField_uname;
    // End of variables declaration//GEN-END:variables
}
